#-------------------------------
# General Site Settings
title: "Mozilla Voice"
description: "The new home for machine-learning based voice technologies - including software, tools, and datasets. Common Voice is Mozilla's global crowdsourcing initiative to build multilingual open voice datasets that help teach machines how real people speak."
open_graph_image: "/images/home/common-voice-bot.png"
open_graph_image_alt: "Mozilla Voice"
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://oi.mozilla.org

#-------------------------------
# Navigation Settings
menu:
  - {title: Projects, url: '/projects.html'}
  - {title: News, url: '/news.html'}
  - {title: Partners, url: '/partners.html'}
  - {title: Community, url: '/community.html'}
  - {title: About, url: '/about.html'}

#-------------------------------
# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compact

include:
  - "_pages"
